### ISSUE TITLE
Spielprinzip

### ISSUE THREAD

**Issue by Firefox0** [Firefox0/unity-project#1]

**Comment by lee-shao** [comment]
- Perspektive (FP/3rdPerson, etc.)?
- Ziel des Spiels?

**Comment by Firefox0** [comment]
- Dynamisch (Temple Run) oder Statisch (Einzelne Levels)

**Comment by lee-shao** [comment]
So hab in ca 30 min was zusammengeschrieben, weil auf abdu einfach kein verlass ist. Es ist erstmal eine Idee wie ich mir das von dem, was abdu erzählt hat, vorgestellt habe. Was nicht passt das können wir natürlich passend machen also wenn du was ändern oder hinzufügen willst kannst einfach ins Pad schreiben.

https://demo.codimd.org/A7pUNcQFTfS26dlCUMHyEQ

**Comment by TheRealCHicKEN** [comment]
[spielprinzip.txt](https://github.com/Firefox0/unity-project/files/5085265/spielprinzip.txt)

**Comment by Firefox0** [comment]
- verschwindende Plattformen (ständig in Bewegung bleiben)
- Luftangriffe (bspw. Meteoriten im Lava-Level)
- Korrektur zu TheRealChicken: Springen doch hinzufügen, mehr Angriffsmöglichkeiten (Welle über den Boden, über die man springen muss)

**Comment by Firefox0** [comment]
- Sternesystem: Bis zu 3 Sterne freischaltbar mit hardgecodeten Zeiten. 1 Minute 1 Stern, 2 Minuten 2 Sterne etc.
- aus dem obigen stellt sich die Frage: viele kleinere Levels, statt wenigen großen Levels? 

- Mobile oder Desktop? Beides?
