### ISSUE TITLE
Level Auswahl

### ISSUE THREAD

**Issue by lee-shao** [Firefox0/unity-project#6]
Erstelle eine neue Szene `Level Auswahl` in der alle Levels als Miniaturbilder zu sehen sind.
Unter jedem Bild soll außerdem Platz für eine kleine Textur sein, die mit Anzahl von Sternen indiziert, wie gut man das Level abgeschlossen hat. 

- 0 Sterne zeigt, dass man das Level noch nicht geschafft hat
- 3 Sterne heißt, dass man eine Top Zeit in dem Level erreicht hat
- 1 Krone zeigt, dass man das Level ohne Schaden geschafft hat

Die Levels werden Zeilenweise angezeigt. Jeweils drei Miniaturbilder pro Zeile.

**Comment by Firefox0** [comment]
Basic Level Auswahl wurde hinzugefügt. Sterne fehlen.
