### ISSUE TITLE
Implement debuff system

### ISSUE THREAD

**Issue by lee-shao** [Firefox0/unity-project#66]
Implement a debuff system which will provide a debuff to the player over a certain duration.

**Comment by Firefox0** [comment]
implemented slow, but its not working properly yet.
slow needs to check remaining time.
example 1 sec 50% slow on player, after 0.5 secs he gets hit by another projectile with a 2 secs 30% slow. after the remaining 0.5 secs (first slow is done), put the remaining 1.5 secs slow of the second projectile on the player.
